# Generated by Django 6.1.1 on 2026-10-01 17:06

import apps.billing.models
import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libredte", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AduanaClausulaVenta",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "cláusula de venta",
                "verbose_name_plural": "cláusulas de venta",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="AduanaFormaPago",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "forma de pago de exportación",
                "verbose_name_plural": "formas de pago de exportación",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="AduanaModalidadVenta",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "modalidad de venta",
                "verbose_name_plural": "modalidades de venta",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="AduanaMoneda",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=20, unique=True)),
                ("codigo_iso", models.CharField(blank=True, max_length=3)),
            ],
            options={
                "verbose_name": "moneda",
                "verbose_name_plural": "monedas",
                "ordering": ["glosa"],
            },
        ),
        migrations.CreateModel(
            name="AduanaPuerto",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "puerto",
                "verbose_name_plural": "puertos",
                "ordering": ["glosa"],
            },
        ),
        migrations.CreateModel(
            name="AduanaTipoBulto",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "tipo de bulto",
                "verbose_name_plural": "tipos de bulto",
                "ordering": ["glosa"],
            },
        ),
        migrations.CreateModel(
            name="AduanaTransporte",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "vía de transporte",
                "verbose_name_plural": "vías de transporte",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="AduanaUnidad",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "unidad de medida",
                "verbose_name_plural": "unidades de medida",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="FormaPago",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "forma de pago",
                "verbose_name_plural": "formas de pago",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="ImpuestoAdicionalRetencion",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("tipo", models.CharField(max_length=1)),
                ("glosa", models.CharField(max_length=100)),
                ("tasa", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                "verbose_name": "impuesto adicional o retención",
                "verbose_name_plural": "impuestos adicionales o retenciones",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="MedioPago",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=2, unique=True)),
                ("glosa", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "medio de pago",
                "verbose_name_plural": "medios de pago",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="TipoDte",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=50)),
                (
                    "glosa_corta",
                    models.CharField(
                        blank=True,
                        help_text='Se autocompleta desde `glosa` al guardar si se deja vacío — mismo criterio que `CodigoDocumento::getNombreCorto()` en libredte-lib-core (Document/Enum): sacar el sufijo " Electrónica" de la glosa oficial del SII.',
                        max_length=50,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tributario", "Tributario"),
                            ("informativo", "Informativo"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "operacion",
                    models.CharField(
                        blank=True,
                        choices=[("suma", "Suma"), ("resta", "Resta")],
                        max_length=5,
                    ),
                ),
                ("compra", models.BooleanField(default=False)),
                ("venta", models.BooleanField(default=False)),
                ("cedible", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "tipo de DTE",
                "verbose_name_plural": "tipos de DTE",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Traslado",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "indicador de traslado",
                "verbose_name_plural": "indicadores de traslado",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Emisor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rut", models.IntegerField()),
                ("dv", apps.core.fields.DvField()),
                ("codigo_interno", models.CharField(blank=True, max_length=20)),
                ("razon_social", models.CharField(blank=True, max_length=100)),
                ("giro", models.CharField(blank=True, max_length=80)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("correo", models.EmailField(blank=True, max_length=80)),
                ("direccion", models.CharField(blank=True, max_length=70)),
                ("ciudad", models.CharField(blank=True, max_length=20)),
                ("numero_identificacion", models.CharField(blank=True, max_length=20)),
                (
                    "comuna",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emisores",
                        to="libredte.comuna",
                    ),
                ),
                (
                    "contribuyente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emisores",
                        to="libredte.contribuyente",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emisores",
                        to="libredte.pais",
                    ),
                ),
            ],
            options={
                "verbose_name": "emisor",
                "verbose_name_plural": "emisores",
            },
        ),
        migrations.CreateModel(
            name="ItemCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=35)),
                ("activa", models.BooleanField(default=True)),
                (
                    "contribuyente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_categorias",
                        to="libredte.contribuyente",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría de ítem",
                "verbose_name_plural": "categorías de ítem",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_tipo", models.CharField(default="INT1", max_length=10)),
                ("codigo", models.CharField(max_length=35)),
                ("nombre", models.CharField(max_length=80)),
                ("descripcion", models.CharField(blank=True, max_length=1000)),
                ("unidad", models.CharField(blank=True, max_length=4)),
                ("precio", models.IntegerField()),
                (
                    "bruto",
                    models.BooleanField(
                        default=False,
                        help_text="Si `precio` ya incluye IVA. Ver `precio_neto`.",
                    ),
                ),
                (
                    "indicador_exencion",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "No afecto o exento de IVA"),
                            (2, "No facturable"),
                            (3, "Garantía por depósito o envase"),
                            (4, "No constituye venta"),
                            (5, "Ítem a rebajar"),
                            (6, "No facturable negativo"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "descuento_tipo",
                    models.CharField(
                        choices=[("%", "Porcentaje"), ("$", "Monto")],
                        default="%",
                        max_length=1,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "contribuyente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="libredte.contribuyente",
                    ),
                ),
                (
                    "impuesto_adicional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="billing.impuestoadicionalretencion",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="billing.itemcategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "ítem",
                "verbose_name_plural": "ítems",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Receptor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rut", models.IntegerField()),
                ("dv", apps.core.fields.DvField()),
                ("codigo_interno", models.CharField(blank=True, max_length=20)),
                ("razon_social", models.CharField(blank=True, max_length=100)),
                ("giro", models.CharField(blank=True, max_length=40)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("correo", models.EmailField(blank=True, max_length=80)),
                ("direccion", models.CharField(blank=True, max_length=70)),
                ("ciudad", models.CharField(blank=True, max_length=20)),
                ("numero_identificacion", models.CharField(blank=True, max_length=20)),
                (
                    "comuna",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptores",
                        to="libredte.comuna",
                    ),
                ),
                (
                    "contribuyente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptores",
                        to="libredte.contribuyente",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptores",
                        to="libredte.pais",
                    ),
                ),
            ],
            options={
                "verbose_name": "receptor",
                "verbose_name_plural": "receptores",
            },
        ),
        migrations.CreateModel(
            name="DteRecibido",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("folio", models.BigIntegerField()),
                ("periodo", models.PositiveIntegerField()),
                ("fecha", models.DateField()),
                ("neto", models.BigIntegerField(blank=True, null=True)),
                ("exento", models.BigIntegerField(blank=True, null=True)),
                ("iva", models.BigIntegerField(default=0)),
                ("total", models.BigIntegerField()),
                (
                    "xml_base64",
                    models.TextField(
                        help_text="XML del DTE en base64, tal cual lo entrega la API."
                    ),
                ),
                ("fecha_registro_rcv", models.DateTimeField(blank=True, null=True)),
                ("fecha_hora_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "contribuyente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dtes_recibidos",
                        to="libredte.contribuyente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dtes_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dtes_recibidos",
                        to="billing.emisor",
                    ),
                ),
                (
                    "tipo_dte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dtes_recibidos",
                        to="billing.tipodte",
                    ),
                ),
            ],
            options={
                "verbose_name": "DTE recibido",
                "verbose_name_plural": "DTE recibidos",
            },
            bases=(apps.billing.models.XmlBase64Mixin, models.Model),
        ),
        migrations.CreateModel(
            name="DteEmitido",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("folio", models.BigIntegerField()),
                ("periodo", models.PositiveIntegerField()),
                ("fecha", models.DateField()),
                ("neto", models.BigIntegerField(blank=True, null=True)),
                ("exento", models.BigIntegerField(blank=True, null=True)),
                ("iva", models.BigIntegerField(default=0)),
                ("total", models.BigIntegerField()),
                (
                    "xml_base64",
                    models.TextField(
                        help_text="XML del DTE en base64, tal cual lo entrega la API."
                    ),
                ),
                ("track_id", models.BigIntegerField(blank=True, null=True)),
                ("revision_estado", models.CharField(blank=True, max_length=100)),
                ("revision_detalle", models.TextField(blank=True)),
                ("fecha_hora_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "contribuyente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dtes_emitidos",
                        to="libredte.contribuyente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dtes_emitidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dtes_emitidos",
                        to="billing.receptor",
                    ),
                ),
                (
                    "tipo_dte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dtes_emitidos",
                        to="billing.tipodte",
                    ),
                ),
            ],
            options={
                "verbose_name": "DTE emitido",
                "verbose_name_plural": "DTE emitidos",
            },
            bases=(apps.billing.models.XmlBase64Mixin, models.Model),
        ),
        migrations.CreateModel(
            name="CafFolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siguiente", models.BigIntegerField()),
                ("disponibles", models.IntegerField()),
                ("alerta", models.IntegerField()),
                ("alertado", models.BooleanField(default=False)),
                (
                    "contribuyente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caf_folios",
                        to="libredte.contribuyente",
                    ),
                ),
                (
                    "tipo_dte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caf_folios",
                        to="billing.tipodte",
                    ),
                ),
            ],
            options={
                "verbose_name": "contador de folios",
                "verbose_name_plural": "contadores de folios",
            },
        ),
        migrations.CreateModel(
            name="Caf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desde", models.BigIntegerField()),
                ("hasta", models.BigIntegerField()),
                (
                    "xml_base64",
                    models.TextField(
                        help_text="XML del CAF en base64, tal cual lo entrega la API."
                    ),
                ),
                (
                    "fecha_autorizacion",
                    models.DateField(
                        help_text="Fecha de autorización del CAF (tag <FA> del XML)."
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True,
                        help_text="Null si el tipo de documento no vence (ver Caf::hasVencimiento() en libredte-lib-core).",
                        null=True,
                    ),
                ),
                (
                    "idk",
                    models.IntegerField(
                        help_text="Identificador de la llave (IDK) del CAF."
                    ),
                ),
                (
                    "contribuyente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cafs",
                        to="libredte.contribuyente",
                    ),
                ),
                (
                    "tipo_dte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cafs",
                        to="billing.tipodte",
                    ),
                ),
            ],
            options={
                "verbose_name": "CAF",
                "verbose_name_plural": "CAF",
            },
            bases=(apps.billing.models.XmlBase64Mixin, models.Model),
        ),
        migrations.CreateModel(
            name="Borrador",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("datos", models.JSONField()),
                ("extra", models.JSONField(blank=True, null=True)),
                (
                    "xml_base64",
                    models.TextField(
                        help_text="XML del borrador (sin timbre) en base64."
                    ),
                ),
                ("neto", models.BigIntegerField(blank=True, null=True)),
                ("exento", models.BigIntegerField(blank=True, null=True)),
                ("iva", models.BigIntegerField(default=0)),
                ("total", models.BigIntegerField()),
                ("fecha_hora_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "contribuyente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borradores",
                        to="libredte.contribuyente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borradores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borradores",
                        to="billing.receptor",
                    ),
                ),
                (
                    "tipo_dte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borradores",
                        to="billing.tipodte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Borrador",
                "verbose_name_plural": "Borradores",
                "ordering": ["-fecha", "-fecha_hora_creacion"],
            },
            bases=(apps.billing.models.XmlBase64Mixin, models.Model),
        ),
        migrations.CreateModel(
            name="DteEmitidoReferencia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tipo_referencia",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="`CodRef` del XML (1=Anula, 2=Corrige texto, 3=Corrige montos).",
                        null=True,
                    ),
                ),
                ("razon", models.CharField(blank=True, max_length=90)),
                (
                    "emitido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referencias",
                        to="billing.dteemitido",
                    ),
                ),
                (
                    "referencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referenciado_por",
                        to="billing.dteemitido",
                    ),
                ),
            ],
            options={
                "verbose_name": "referencia de DTE emitido",
                "verbose_name_plural": "referencias de DTE emitido",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("emitido", "referencia"),
                        name="dte_emitido_referencia_unica",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DteRecibidoRcvEvento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("ERM", "Entrega Real de Mercaderías o Servicios"),
                            ("ACD", "Acepta Contenido del Documento"),
                            ("RCD", "Reclamo al Contenido del Documento"),
                            ("RFP", "Reclamo por Falta Parcial de Mercaderías"),
                            ("RFT", "Reclamo por Falta Total de Mercaderías"),
                        ],
                        max_length=3,
                    ),
                ),
                ("responsable", models.CharField(max_length=12)),
                ("fecha", models.DateTimeField()),
                ("fecha_hora_sincronizado", models.DateTimeField(auto_now_add=True)),
                (
                    "dte_recibido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rcv_eventos",
                        to="billing.dterecibido",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento RCV de DTE recibido",
                "verbose_name_plural": "eventos RCV de DTE recibido",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dte_recibido", "codigo", "responsable", "fecha"),
                        name="dte_recibido_rcv_evento_unico",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="emisor",
            constraint=models.UniqueConstraint(
                fields=("contribuyente", "codigo_interno"),
                name="emisor_unico_por_contribuyente_y_codigo_interno",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemcategoria",
            constraint=models.UniqueConstraint(
                fields=("contribuyente", "nombre"),
                name="categoria_item_unica_por_contribuyente_y_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("contribuyente", "codigo_tipo", "codigo"),
                name="item_unico_por_contribuyente_tipo_y_codigo",
            ),
        ),
        migrations.AddConstraint(
            model_name="receptor",
            constraint=models.UniqueConstraint(
                fields=("contribuyente", "codigo_interno"),
                name="receptor_unico_por_contribuyente_y_codigo_interno",
            ),
        ),
        migrations.AddConstraint(
            model_name="dterecibido",
            constraint=models.UniqueConstraint(
                fields=("contribuyente", "emisor", "tipo_dte", "folio"),
                name="dte_recibido_unico_por_contribuyente_emisor_tipo_dte_y_folio",
            ),
        ),
        migrations.AddConstraint(
            model_name="dteemitido",
            constraint=models.UniqueConstraint(
                fields=("contribuyente", "tipo_dte", "folio"),
                name="dte_emitido_unico_por_contribuyente_tipo_dte_y_folio",
            ),
        ),
        migrations.AddConstraint(
            model_name="caffolio",
            constraint=models.UniqueConstraint(
                fields=("contribuyente", "tipo_dte"),
                name="caf_folio_unico_por_contribuyente_y_tipo_dte",
            ),
        ),
        migrations.AddConstraint(
            model_name="caf",
            constraint=models.UniqueConstraint(
                fields=("contribuyente", "tipo_dte", "desde"),
                name="caf_unico_por_contribuyente_tipo_dte_y_desde",
            ),
        ),
    ]
