from django.urls import path

from ..views import app as views

app_name = 'billing'

urlpatterns = [
    path('emitidos/', views.emitidos, name='emitidos'),
    path(
        'emitidos/subir/',
        views.emitido_subir,
        name='emitido_subir',
    ),
    path(
        'emitidos/<int:pk>/',
        views.emitido_detalle,
        name='emitido_detalle',
    ),
    path(
        'emitidos/<int:pk>/xml/',
        views.emitido_descargar_xml,
        name='emitido_descargar_xml',
    ),
    path(
        'emitidos/<int:pk>/render/',
        views.emitido_render_html,
        name='emitido_render_html',
    ),
    path(
        'emitidos/<int:pk>/pdf/',
        views.emitido_descargar_pdf,
        name='emitido_descargar_pdf',
    ),
    path(
        'emitidos/<int:pk>/enviar-sii/',
        views.emitido_enviar_sii,
        name='emitido_enviar_sii',
    ),
    path(
        'emitidos/<int:pk>/actualizar-estado/',
        views.emitido_actualizar_estado,
        name='emitido_actualizar_estado',
    ),
    path('receptores/', views.receptores, name='receptores'),
    path(
        'receptores/nuevo/',
        views.ReceptorCreateView.as_view(),
        name='receptor_nuevo',
    ),
    path(
        'receptores/<int:pk>/',
        views.receptor_detalle,
        name='receptor_detalle',
    ),
    path(
        'receptores/<int:pk>/editar/',
        views.ReceptorUpdateView.as_view(),
        name='receptor_editar',
    ),
    path(
        'receptores/<int:pk>/eliminar/',
        views.ReceptorDeleteView.as_view(),
        name='receptor_eliminar',
    ),
    path('emitir/', views.emitir, name='emitir'),
    path(
        'emitir/calcular/',
        views.emitir_calcular,
        name='emitir_calcular',
    ),
    path(
        'emitir/masivo/',
        views.emitir_masivo,
        name='emitir_masivo',
    ),
    path(
        'emitir/masivo/plantilla/<str:extension>/',
        views.emitir_masivo_plantilla,
        name='emitir_masivo_plantilla',
    ),
    path(
        'emitir/masivo/pdf/<str:token>/',
        views.emitir_masivo_pdf,
        name='emitir_masivo_pdf',
    ),
    path('borradores/', views.borradores, name='borradores'),
    path(
        'borradores/<int:pk>/',
        views.borrador_detalle,
        name='borrador_detalle',
    ),
    path(
        'borradores/<int:pk>/render/',
        views.borrador_render_html,
        name='borrador_render_html',
    ),
    path(
        'borradores/<int:pk>/xml/',
        views.borrador_descargar_xml,
        name='borrador_descargar_xml',
    ),
    path(
        'borradores/<int:pk>/pdf/',
        views.borrador_descargar_pdf,
        name='borrador_descargar_pdf',
    ),
    path(
        'borradores/<int:pk>/json/normalizado/',
        views.borrador_descargar_json_normalizado,
        name='borrador_descargar_json_normalizado',
    ),
    path(
        'borradores/<int:pk>/json/extra/',
        views.borrador_descargar_json_extra,
        name='borrador_descargar_json_extra',
    ),
    path(
        'borradores/<int:pk>/confirmar/',
        views.borrador_confirmar,
        name='borrador_confirmar',
    ),
    path(
        'borradores/<int:pk>/eliminar/',
        views.BorradorDeleteView.as_view(),
        name='borrador_eliminar',
    ),
    path('recibidos/', views.recibidos, name='recibidos'),
    path(
        'recibidos/subir/',
        views.recibido_subir,
        name='recibido_subir',
    ),
    path(
        'recibidos/<int:pk>/',
        views.recibido_detalle,
        name='recibido_detalle',
    ),
    path(
        'recibidos/<int:pk>/xml/',
        views.recibido_descargar_xml,
        name='recibido_descargar_xml',
    ),
    path(
        'recibidos/<int:pk>/render/',
        views.recibido_render_html,
        name='recibido_render_html',
    ),
    path(
        'recibidos/<int:pk>/pdf/',
        views.recibido_descargar_pdf,
        name='recibido_descargar_pdf',
    ),
    path('ventas/', views.ventas, name='ventas'),
    path('ventas/registro/', views.ventas_registro, name='ventas_registro'),
    path(
        'ventas/<int:periodo>/',
        views.ventas_periodo,
        name='ventas_periodo',
    ),
    path(
        'ventas/<int:periodo>/rcv/resumen/',
        views.ventas_periodo_rcv_resumen,
        name='ventas_periodo_rcv_resumen',
    ),
    path(
        'ventas/<int:periodo>/rcv/detalle/<int:dte>/',
        views.ventas_periodo_rcv_detalle,
        name='ventas_periodo_rcv_detalle',
    ),
    path('compras/', views.compras, name='compras'),
    path('compras/registro/', views.compras_registro, name='compras_registro'),
    path(
        'compras/<int:periodo>/',
        views.compras_periodo,
        name='compras_periodo',
    ),
    path(
        'compras/<int:periodo>/rcv/resumen/',
        views.compras_periodo_rcv_resumen,
        name='compras_periodo_rcv_resumen',
    ),
    path(
        'compras/<int:periodo>/rcv/resumen/<str:estado>/',
        views.compras_periodo_rcv_resumen,
        name='compras_periodo_rcv_resumen',
    ),
    path(
        'compras/<int:periodo>/rcv/detalle/<int:dte>/',
        views.compras_periodo_rcv_detalle,
        name='compras_periodo_rcv_detalle',
    ),
    path(
        'compras/<int:periodo>/rcv/detalle/<int:dte>/<str:estado>/',
        views.compras_periodo_rcv_detalle,
        name='compras_periodo_rcv_detalle',
    ),
    path('emisores/', views.emisores, name='emisores'),
    path(
        'emisores/<int:pk>/',
        views.emisor_detalle,
        name='emisor_detalle',
    ),
]
