"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from socket import gethostbyname, gethostname
from typing import Any

from django.contrib.messages import constants as message_constants
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from kombu import Queue

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# `.env` es solo para desarrollo local (no se commitea, ver
# .env.example) — no pisa una env var que el proceso ya traiga seteada
# (ej. en producción, donde no hay `.env` de todos modos).
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# El valor `django-insecure-...` es solo el fallback de desarrollo
# (generado por `startproject`) — cualquier despliegue real debe
# definir `SECRET_KEY` en el entorno (o en `.env`, ver `.env.example`).
_INSECURE_SECRET_KEY = (
    'django-insecure-07vz)&t&gr$q)shzaba!*_$fmqx1me2-=usw5bnf=#7uol9mqx'
)
SECRET_KEY = os.environ.get('SECRET_KEY', _INSECURE_SECRET_KEY)

# Key de cifrado en reposo para `apps.core.fields.EncryptedTextField`
# (independiente de `SECRET_KEY` — rotar una no debe invalidar la otra).
# El valor de acá es solo el fallback de desarrollo — cualquier
# despliegue real debe definir `FIELD_ENCRYPTION_KEY` en el entorno (o
# en `.env`, ver `.env.example`). Generar una nueva con
# `Fernet.generate_key()`.
_INSECURE_FIELD_ENCRYPTION_KEY = '0jTo_joxI5mzGZSb7AWEQeaeCCEXdy9XyUWsEgvk0To='
FIELD_ENCRYPTION_KEY = os.environ.get(
    'FIELD_ENCRYPTION_KEY',
    _INSECURE_FIELD_ENCRYPTION_KEY,
)

# SECURITY WARNING: don't run with debug turned on in production!
# Encendido es solo el fallback de desarrollo: un despliegue real define
# `DEBUG=0` en el entorno.
DEBUG = os.environ.get('DEBUG', '1') == '1'

# Sin `DEBUG`, los fallbacks de arriba son valores públicos (están en el
# repositorio): la app no arranca con ellos.
if not DEBUG and (
    SECRET_KEY == _INSECURE_SECRET_KEY
    or FIELD_ENCRYPTION_KEY == _INSECURE_FIELD_ENCRYPTION_KEY
):
    raise ImproperlyConfigured(
        'Con DEBUG=0 se deben definir SECRET_KEY y FIELD_ENCRYPTION_KEY '
        '(los valores por defecto son públicos).'
    )

# Dominios del sitio, separados por espacio. El primero es el canónico:
# con él y `URL_SCHEMA` se arman los enlaces absolutos que salen fuera
# de un request (el worker no tiene uno del que sacar el dominio), como
# el de descarga de los PDF de la emisión masiva. Las variables llevan
# el prefijo `SITE_` porque `HOSTNAME` ya lo define el sistema (en
# Docker, con el id del contenedor). Los valores de acá son el fallback
# de desarrollo.
HOSTNAME = os.environ.get('SITE_HOSTNAME', 'localhost:8000').split(' ')
URL_SCHEMA = os.environ.get('SITE_URL_SCHEMA', 'http')


def _sin_puerto(host: str) -> str:
    """El host sin `:puerto` (`ALLOWED_HOSTS` no admite puertos)."""
    if host.endswith(']'):
        return host
    return host.partition(':')[0]


# Solo los dominios del sitio, los extra (`SITE_EXTRA_HOSTS`, separados
# por espacio) y los de loopback/máquina (healthchecks) — nunca `*`: con
# el `Host` de la petición se arman, por ejemplo, los enlaces de
# recuperación de contraseña.
ALLOWED_HOSTS = [
    *(_sin_puerto(host) for host in HOSTNAME),
    *os.environ.get('SITE_EXTRA_HOSTS', '').split(),
    'localhost',
    '127.0.0.1',
    '::1',
    gethostname(),
    gethostbyname(gethostname()),
]

# Orígenes desde los que Django acepta un `POST` (verificación CSRF): el
# esquema y los dominios del sitio, con su puerto si lo llevan.
CSRF_TRUSTED_ORIGINS = [f'{URL_SCHEMA}://{host}' for host in HOSTNAME]

# `SITE_BEHIND_PROXY=1` cuando un proxy inverso (Caddy, Traefik, nginx)
# termina el TLS y reenvía `X-Forwarded-Proto`. Django solo confía en esa
# cabecera si el proxy es el único que alcanza a la app (si no, cualquier
# cliente podría falsearla): por eso no se activa por defecto.
if os.environ.get('SITE_BEHIND_PROXY', '0') == '1':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Con el sitio en HTTPS, las cookies de sesión y CSRF no viajan por HTTP.
if URL_SCHEMA == 'https':
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    # Esquema OpenAPI de la API pública (ver `SPECTACULAR_SETTINGS`).
    'drf_spectacular',
    # Token de API por usuario — se emite desde el perfil y solo
    # autentica en las vistas que heredan de `apps/core/api.py`.
    'rest_framework.authtoken',
    # Resultados de las tareas Celery en la base de datos.
    'django_celery_results',
    'apps.core',
    'apps.public',
    'apps.libredte',
    'apps.billing',
    'apps.accounting',
    'apps.human_resources',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# El default es solo sesión a propósito, aunque hoy toda la API acepte
# token: así una vista nueva nace cerrada a clientes externos y
# publicarla es un acto explícito (heredar de `PublicApiMixin`, ver
# `apps/core/api.py`) que se ve leyendo la vista, no algo que pasa por
# omisión al agregarla.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# Documentación de la API
# https://drf-spectacular.readthedocs.io/

# La prosa larga (introducción, autenticación, paginación) vive en
# archivos Markdown y no acá: se editan sin tocar settings, y el prefijo
# numérico del nombre fija el orden en que se concatenan.
OPENAPI_DOCS_PATH = BASE_DIR / 'apps' / 'core' / 'api_docs'
OPENAPI_DESCRIPTION = '\n\n'.join(
    archivo.read_text(encoding='utf-8')
    for archivo in sorted(OPENAPI_DOCS_PATH.glob('*.md'))
)

SPECTACULAR_SETTINGS = {
    'TITLE': 'API de LibreDTE Slim',
    'DESCRIPTION': OPENAPI_DESCRIPTION,
    'VERSION': '1.0.0',
    # El esquema en sí no se publica como un endpoint más dentro del
    # propio esquema.
    'SERVE_INCLUDE_SCHEMA': False,
    # Respeta el orden de `urls.py` en vez de alfabetizar: los
    # documentos emitidos importan más que las categorías de ítems.
    'SORT_OPERATIONS': False,
    # Solo el token llega al esquema. `SessionAuthentication` también
    # está activa —la usa el JS de la propia app— pero a un cliente
    # externo no le sirve, y sin esto aparecía documentada como un
    # `cookieAuth` que nadie que lea esto puede usar.
    'AUTHENTICATION_WHITELIST': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # Pisa la descripción en inglés que trae drf-spectacular, sin crear
    # un segundo esquema: la clave es la misma que genera él.
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'tokenAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'Authorization',
                'description': 'Prefijo `Token`, ej. `Token abc123...`.',
            },
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.core.middleware.RequireInitialUserMiddleware',
    'apps.libredte.middleware.RequireContribuyenteMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.libredte.context_processors.current_contribuyente',
                'apps.core.context_processors.menu_sections',
                'apps.core.context_processors.settings_sections',
                'apps.core.context_processors.app_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# `DB_ENGINE=postgresql` (+ `DB_NAME`/`DB_USER`/`DB_PASSWORD`/`DB_HOST`/
# `DB_PORT`) para producción — sin definir, sqlite (default de
# desarrollo, cero setup). El driver (`psycopg`) ya viene instalado
# siempre, así que activar Postgres es solo cambiar estas env vars.
if os.environ.get('DB_ENGINE') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'libredte_slim'),
            'USER': os.environ.get('DB_USER', 'libredte_slim'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Destino de `collectstatic`. En producción los sirve el servidor web (no
# la app), por eso es configurable: un volumen compartido con él.
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles'))


# Media files (contenido subido por el usuario, ej. `Contribuyente.logo`)
# https://docs.djangoproject.com/en/6.1/topics/files/

MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))


# Messages
# https://docs.djangoproject.com/en/6.1/ref/contrib/messages/
#
# Django usa `error` como tag para `messages.error()`, pero las clases
# de alerta de Bootstrap son `alert-danger`/`alert-success`/etc. — sin
# este mapeo, `alert-error` no matchea ninguna clase de Bootstrap y el
# mensaje queda sin estilo.

MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}


# Auth
# https://docs.djangoproject.com/en/6.1/topics/auth/default/

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'public:welcome'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Con `EMAIL_HOST` se envía por SMTP; sin él, los correos se imprimen en
# consola. Se leen como variables locales porque Django no arranca si
# los settings `EMAIL_*` (deprecados) conviven con `MAILERS`.

_mailer: dict[str, Any]
_email_host = os.environ.get('EMAIL_HOST')
if _email_host:
    _email_port = os.environ.get('EMAIL_PORT')
    _mailer = {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {
            'host': _email_host,
            # Sin puerto, Django lo deduce de SSL/TLS.
            'port': int(_email_port) if _email_port else None,
            'use_ssl': os.environ.get('EMAIL_USE_SSL', '0') == '1',
            'use_tls': os.environ.get('EMAIL_USE_TLS', '0') == '1',
            'username': os.environ.get('EMAIL_HOST_USER', ''),
            'password': os.environ.get('EMAIL_HOST_PASSWORD', ''),
            'timeout': 30,
        },
    }
else:
    _mailer = {'BACKEND': 'django.core.mail.backends.console.EmailBackend'}

MAILERS = {'default': _mailer}

# Por defecto, la cuenta que autentica: muchos proveedores rechazan otro
# remitente.
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    os.environ.get('EMAIL_HOST_USER', 'webmaster@localhost'),
)


# Backend por defecto de la capability `libredte.backend`.

PLUGIN_LIBREDTE_BACKEND_API_URL = os.environ.get(
    'PLUGIN_LIBREDTE_BACKEND_API_URL',
    'https://core.libredte.cl/api',
)
PLUGIN_LIBREDTE_BACKEND_API_TOKEN = os.environ.get(
    'PLUGIN_LIBREDTE_BACKEND_API_TOKEN',
    '',
)
PLUGIN_LIBREDTE_BACKEND_API_AUTH_SCHEME = os.environ.get(
    'PLUGIN_LIBREDTE_BACKEND_API_AUTH_SCHEME',
    'Bearer',
)


# Backend por defecto de la capability `sii.backend`.

PLUGIN_APIGATEWAYCL_API_URL = os.environ.get(
    'PLUGIN_APIGATEWAYCL_API_URL',
    'https://app.apigateway.cl',
)
PLUGIN_APIGATEWAYCL_API_TOKEN = os.environ.get(
    'PLUGIN_APIGATEWAYCL_API_TOKEN',
    '',
)


# Cola de tareas (ver `config/celery.py`): broker en Redis, resultados
# en la base de datos.

CELERY_BROKER_URL = os.environ.get(
    'CELERY_BROKER_URL',
    'redis://localhost:6379/0',
)
CELERY_RESULT_BACKEND = 'django-db'

# Cada tarea elige su cola con `@shared_task(queue=...)`; si no, va a
# `default`.
CELERY_TASK_QUEUES = (
    Queue('default'),
    Queue('emision_masiva'),
)
CELERY_TASK_DEFAULT_QUEUE = 'default'

# Registra cuándo empieza cada tarea, y su nombre y argumentos.
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_EXTENDED = True

# Plazo tras el cual Redis devuelve a la cola una tarea reservada que no
# se confirmó.
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
}

# El worker reintenta conectarse al arrancar; encolar desde la web falla
# rápido si Redis no responde, en vez de colgar el request.
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_TIMEOUT = 5

# Caché en el mismo Redis, compartida entre la web y los workers.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': CELERY_BROKER_URL,
        'KEY_PREFIX': 'libredte_slim',
        'OPTIONS': {
            'socket_connect_timeout': 5,
            'socket_timeout': 5,
        },
    },
}


# Emisión masiva: el ZIP con los PDF no va adjunto al correo, queda en
# `EMISION_MASIVA_PDF_DIR`, en una carpeta por contribuyente (su RUT),
# y el correo lleva un enlace firmado para descargarlo (ver
# `bulk_biller.find_pdf_zip()`). La carpeta no se publica (no está bajo `MEDIA_ROOT`) y tiene que ser la
# misma para el proceso web y el worker: en Docker, un volumen
# compartido.
EMISION_MASIVA_PDF_DIR = Path(
    os.environ.get(
        'EMISION_MASIVA_PDF_DIR',
        BASE_DIR / 'storage' / 'emision_masiva/pdf',
    ),
)


# Logs a consola (stdout), que es de donde los recoge Docker. Nivel de
# la app con `LOG_LEVEL`. Los errores 5xx de `django.request` salen con
# su traza.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('LOG_LEVEL', 'INFO').upper(),
    },
}
