# Generated by Django 6.1.1 on 2026-10-01 17:06

import apps.core.fields
import apps.libredte.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActividadEconomica",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=150)),
                ("afecta_iva", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "actividad económica",
                "verbose_name_plural": "actividades económicas",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Comuna",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=60, unique=True)),
                ("glosa", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name": "comuna",
                "verbose_name_plural": "comunas",
                "ordering": ["glosa"],
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveSmallIntegerField(unique=True)),
                ("glosa", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name": "país",
                "verbose_name_plural": "países",
                "ordering": ["glosa"],
            },
        ),
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificado_id", models.CharField(max_length=20)),
                ("nombre", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "issuer",
                    models.CharField(
                        blank=True,
                        help_text="Autoridad certificadora que emitió el certificado.",
                        max_length=150,
                    ),
                ),
                ("x509", models.TextField(help_text="Certificado X.509 en PEM.")),
                (
                    "clave_privada",
                    apps.core.fields.EncryptedTextField(
                        help_text="Clave privada en PEM, cifrada en reposo."
                    ),
                ),
                ("valido_desde", models.DateTimeField(blank=True, null=True)),
                ("valido_hasta", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "certificado",
                "verbose_name_plural": "certificados",
            },
        ),
        migrations.CreateModel(
            name="Contribuyente",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rut", models.IntegerField(unique=True)),
                ("dv", apps.core.fields.DvField()),
                ("razon_social", models.CharField(max_length=100)),
                ("giro", models.CharField(max_length=80)),
                ("direccion", models.CharField(max_length=70)),
                ("nombre_fantasia", models.CharField(blank=True, max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Máximo 500x200px y 100 KB.",
                        storage=apps.libredte.models.OverwriteStorage(),
                        upload_to=apps.libredte.models._logo_upload_to,
                        validators=[
                            apps.libredte.models._validar_tamano_logo,
                            apps.libredte.models._validar_dimensiones_logo,
                        ],
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("correo", models.EmailField(blank=True, max_length=80)),
                ("sitio_web", models.URLField(blank=True)),
                (
                    "autorizacion_dte_resolucion_fecha",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "autorizacion_dte_resolucion_numero",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "certificado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contribuyentes",
                        to="libredte.certificado",
                    ),
                ),
                (
                    "comuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contribuyentes",
                        to="libredte.comuna",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contribuyentes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contribuyente",
                "verbose_name_plural": "contribuyentes",
            },
        ),
        migrations.CreateModel(
            name="ContribuyenteActividadEconomica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_principal", models.BooleanField(default=False)),
                (
                    "actividad_economica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contribuyentes_actividades",
                        to="libredte.actividadeconomica",
                    ),
                ),
                (
                    "contribuyente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="libredte.contribuyente",
                    ),
                ),
            ],
            options={
                "verbose_name": "actividad económica de contribuyente",
                "verbose_name_plural": "actividades económicas de contribuyente",
            },
        ),
        migrations.AddField(
            model_name="contribuyente",
            name="actividades_economicas",
            field=models.ManyToManyField(
                related_name="contribuyentes",
                through="libredte.ContribuyenteActividadEconomica",
                to="libredte.actividadeconomica",
            ),
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_sii", models.PositiveIntegerField(blank=True, null=True)),
                ("es_matriz", models.BooleanField(default=False)),
                ("nombre", models.CharField(blank=True, max_length=20)),
                ("direccion", models.CharField(max_length=70)),
                ("ciudad", models.CharField(blank=True, max_length=20)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("correo", models.EmailField(blank=True, max_length=80)),
                (
                    "comuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sucursales",
                        to="libredte.comuna",
                    ),
                ),
                (
                    "contribuyente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursales",
                        to="libredte.contribuyente",
                    ),
                ),
            ],
            options={
                "verbose_name": "sucursal",
                "verbose_name_plural": "sucursales",
            },
        ),
        migrations.AddConstraint(
            model_name="certificado",
            constraint=models.UniqueConstraint(
                fields=("usuario", "certificado_id"),
                name="certificado_unico_por_usuario",
            ),
        ),
        migrations.AddConstraint(
            model_name="contribuyenteactividadeconomica",
            constraint=models.UniqueConstraint(
                fields=("contribuyente", "actividad_economica"),
                name="actividad_unica_por_contribuyente",
            ),
        ),
        migrations.AddConstraint(
            model_name="contribuyenteactividadeconomica",
            constraint=models.UniqueConstraint(
                condition=models.Q(("es_principal", True)),
                fields=("contribuyente",),
                name="una_actividad_principal_por_contribuyente",
            ),
        ),
        migrations.AddConstraint(
            model_name="sucursal",
            constraint=models.UniqueConstraint(
                fields=("contribuyente", "codigo_sii"),
                name="sucursal_unica_por_contribuyente_y_codigo_sii",
            ),
        ),
        migrations.AddConstraint(
            model_name="sucursal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("es_matriz", True)),
                fields=("contribuyente",),
                name="una_matriz_por_contribuyente",
            ),
        ),
    ]
